# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ddelap_C <- function(x, alpha, beta, lambda, lg) {
    .Call('Delaporte_ddelap_C', PACKAGE = 'Delaporte', x, alpha, beta, lambda, lg)
}

pdelap_C <- function(q, alpha, beta, lambda, lt, lp) {
    .Call('Delaporte_pdelap_C', PACKAGE = 'Delaporte', q, alpha, beta, lambda, lt, lp)
}

